name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
    if: github.event.deployment.environment != 'Production'
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'Preview Env'

